# Run MAGICC
In this notebook, we will run MAGICC for a single scenario for a small number of ensemble members for MAGICC7.

In [1]:
ENSEMBLE_MEMBERS = 600
MODEL = "AIM/CGE V2.2"
SCENARIO = "ENGAGE-Feasibility-Maximum-Effort/Institutional_NZCO2"
FILE = "output/102_netzero_co2_extended.csv"
CO2_ONLY = False

In [2]:
import multiprocessing
import os
import platform
from functools import partial
from pathlib import Path

import openscm_units
import pandas_indexing as pix
import pandas_openscm
import pint
import seaborn as sns
from pandas_openscm.io import load_timeseries_csv
import pandas as pd

import gcages.cmip7_scenariomip.pre_processing.reaggregation.basic
from gcages.cmip7_scenariomip.harmonisation import (
    create_cmip7_scenariomip_global_harmoniser,
)
from gcages.cmip7_scenariomip.infilling import CMIP7ScenarioMIPInfiller
from gcages.cmip7_scenariomip.post_processing import CMIP7ScenarioMIPPostProcessor
from gcages.cmip7_scenariomip.pre_processing import CMIP7ScenarioMIPPreProcessor
from gcages.cmip7_scenariomip.scm_running import CMIP7ScenarioMIPSCMRunner
from gcages.index_manipulation import split_sectors

In [3]:
BASE_DIR = Path("../../gcages/tests/regression/cmip7-scenariomip/cmip7-scenariomip-workflow-inputs")
CMIP7_SCENARIOMIP_GLOBAL_HISTORICAL_EMISSIONS = BASE_DIR / "history_cmip7_scenariomip.csv"

In [4]:
start = load_timeseries_csv(
    FILE,
    index_columns=["model", "scenario", "region", "variable", "unit"],
    out_columns_type=int,
    out_columns_name="year"
)

In [5]:
scenario_to_run = (
    start
    .loc[
        pd.IndexSlice[MODEL, SCENARIO, :, :, :], :
    ]
)

In [6]:
scenario_to_run

year                                                                                                                    2023  \
model        scenario                                           region variable                unit
AIM/CGE V2.2 ENGAGE-Feasibility-Maximum-Effort/Institutional... World  Emissions|BC            Mt BC/yr             7.219245
                                                                       Emissions|C2F6          kt C2F6/yr           2.431873
                                                                       Emissions|C3F8          kt C3F8/yr           0.721178
                                                                       Emissions|C4F10         kt C4F10/yr          0.101586
                                                                       Emissions|C5F12         kt C5F12/yr          0.061383
                                                                       Emissions|C6F14         kt C6F14/yr          0.062998
                                                                       Emissions|C7F16         kt C7F16/yr          0.186453
                                                                       Emissions|C8F18         kt C8F18/yr          0.136638
                                                                       Emissions|CCl4          kt CCl4/yr          40.297308
                                                                       Emissions|CF4           kt CF4/yr           15.117718
                                                                       Emissions|CFC11         kt CFC11/yr         55.993337
                                                                       Emissions|CFC113        kt CFC113/yr         2.030656
                                                                       Emissions|CFC114        kt CFC114/yr         0.873953
                                                                       Emissions|CFC115        kt CFC115/yr         0.027629
                                                                       Emissions|CFC12         kt CFC12/yr         20.278901
                                                                       Emissions|CH2Cl2        kt CH2Cl2/yr      1612.125558
                                                                       Emissions|CH3Br         kt CH3Br/yr        140.486974
                                                                       Emissions|CH3CCl3       kt CH3CCl3/yr        1.925368
                                                                       Emissions|CH3Cl         kt CH3Cl/yr       5376.602241
                                                                       Emissions|CH4           Mt CH4/yr          363.489901
                                                                       Emissions|CHCl3         kt CHCl3/yr        400.499380
                                                                       Emissions|CO            Mt CO/yr           774.053434
                                                                       Emissions|CO2|Biosphere Mt CO2/yr         3627.550667
                                                                       Emissions|CO2|Fossil    Mt CO2/yr        38712.217040
                                                                       Emissions|HCFC141b      kt HCFC141b/yr      57.429166
                                                                       Emissions|HCFC142b      kt HCFC142b/yr      20.176795
                                                                       Emissions|HCFC22        kt HCFC22/yr       324.526866
                                                                       Emissions|HFC125        kt HFC125/yr       124.074300
                                                                       Emissions|HFC134a       kt HFC134a/yr      291.788600
                                                                       Emissions|HFC143a       kt HFC143a/yr       35.833800
                                                                       Emissions|HFC152a       kt HFC152a/yr       54.869900
                                                                       Emissions|HFC227ea      kt HFC227ea/yr       6.645300
                                                                       Emissions|HFC23         kt HFC23/yr         14.051843
                                                                       Emissions|HFC236fa      kt HFC236fa/yr       0.354300
                                                                       Emissions|HFC245fa      kt HFC245fa/yr      15.504500
                                                                       Emissions|HFC32         kt HFC32/yr        105.566000
                                                                       Emissions|HFC365mfc     kt HFC365mfc/yr      5.241900
                                                                       Emissions|HFC4310mee    kt HFC4310/yr        0.882600
                                                                       Emissions|Halon1202     kt Halon1202/yr      0.000000
                                                                       Emissions|Halon1211     kt Halon1211/yr      2.562978
                                                                       Emissions|Halon1301     kt Halon1301/yr      1.232019
                                                                       Emissions|Halon2402     kt Halon2402/yr      0.000000
                                                                       Emissions|N2O           kt N2O/yr        11289.003671
                                                                       Emissions|NF3           kt NF3/yr            4.010291
                                                                       Emissions|NH3           Mt NH3/yr           69.113401
                                                                       Emissions|NMVOC         Mt VOC/yr          191.244286
                                                                       Emissions|NOx           Mt NO2/yr          127.510494
                                                                       Emissions|OC            Mt OC/yr            34.147891
                                                                       Emissions|SF6           kt SF6/yr            9.352094
                                                                       Emissions|SO2F2         kt SO2F2/yr          4.594033
                                                                       Emissions|SOx           Mt SO2/yr           71.902038
                                                                       Emissions|cC4F8         kt cC4F8/yr          2.248599

year                                                                                                                    2024  \
model        scenario                                           region variable                unit
AIM/CGE V2.2 ENGAGE-Feasibility-Maximum-Effort/Institutional... World  Emissions|BC            Mt BC/yr             7.085110
                                                                       Emissions|C2F6          kt C2F6/yr           2.474856
                                                                       Emissions|C3F8          kt C3F8/yr           0.733925
                                                                       Emissions|C4F10         kt C4F10/yr          0.103382
                                                                       Emissions|C5F12         kt C5F12/yr          0.062468
                                                                       Emissions|C6F14         kt C6F14/yr          0.062998
                                                                       Emissions|C7F16         kt C7F16/yr          0.189749
                                                                       Emissions|C8F18         kt C8F18/yr          0.139053
                                                                       Emissions|CCl4          kt CCl4/yr          37.507899
                                                                       Emissions|CF4           kt CF4/yr           15.468488
                                                                       Emissions|CFC11         kt CFC11/yr         53.802418
                                                                       Emissions|CFC113        kt CFC113/yr         2.624086
                                                                       Emissions|CFC114        kt CFC114/yr         1.124991
                                                                       Emissions|CFC115        kt CFC115/yr         0.026451
                                                                       Emissions|CFC12         kt CFC12/yr         18.606179
                                                                       Emissions|CH2Cl2        kt CH2Cl2/yr      1723.690473
                                                                       Emissions|CH3Br         kt CH3Br/yr        140.445253
                                                                       Emissions|CH3CCl3       kt CH3CCl3/yr        1.984467
                                                                       Emissions|CH3Cl         kt CH3Cl/yr       5376.602241
                                                                       Emissions|CH4           Mt CH4/yr          345.215291
                                                                       Emissions|CHCl3         kt CHCl3/yr        402.964428
                                                                       Emissions|CO            Mt CO/yr           765.240952
                                                                       Emissions|CO2|Biosphere Mt CO2/yr         3531.003179
                                                                       Emissions|CO2|Fossil    Mt CO2/yr        37710.359623
                                                                       Emissions|HCFC141b      kt HCFC141b/yr      57.680778
                                                                       Emissions|HCFC142b      kt HCFC142b/yr      20.998765
                                                                       Emissions|HCFC22        kt HCFC22/yr       323.798943
                                                                       Emissions|HFC125        kt HFC125/yr       151.705204
                                                                       Emissions|HFC134a       kt HFC134a/yr      315.105088
                                                                       Emissions|HFC143a       kt HFC143a/yr       27.090899
                                                                       Emissions|HFC152a       kt HFC152a/yr       44.954178
                                                                       Emissions|HFC227ea      kt HFC227ea/yr       7.805185
                                                                       Emissions|HFC23         kt HFC23/yr         14.343063
                                                                       Emissions|HFC236fa      kt HFC236fa/yr       0.312754
                                                                       Emissions|HFC245fa      kt HFC245fa/yr      13.686425
                                                                       Emissions|HFC32         kt HFC32/yr        135.382668
                                                                       Emissions|HFC365mfc     kt HFC365mfc/yr      5.660774
                                                                       Emissions|HFC4310mee    kt HFC4310/yr        0.723102
                                                                       Emissions|Halon1202     kt Halon1202/yr      0.000000
                                                                       Emissions|Halon1211     kt Halon1211/yr      2.471289
                                                                       Emissions|Halon1301     kt Halon1301/yr      1.165094
                                                                       Emissions|Halon2402     kt Halon2402/yr      0.000000
                                                                       Emissions|N2O           kt N2O/yr        10922.943033
                                                                       Emissions|NF3           kt NF3/yr            4.076949
                                                                       Emissions|NH3           Mt NH3/yr           68.905233
                                                                       Emissions|NMVOC         Mt VOC/yr          189.257059
                                                                       Emissions|NOx           Mt NO2/yr          125.504982
                                                                       Emissions|OC            Mt OC/yr            33.685047
                                                                       Emissions|SF6           kt SF6/yr            9.507541
                                                                       Emissions|SO2F2         kt SO2F2/yr          4.700701
                                                                       Emissions|SOx           Mt SO2/yr           69.294852
                                                                       Emissions|cC4F8         kt cC4F8/yr          2.300809

year                                                                                                                    2025  \
model        scenario                                           region variable                unit
AIM/CGE V2.2 ENGAGE-Feasibility-Maximum-Effort/Institutional... World  Emissions|BC            Mt BC/yr             6.955841
                                                                       Emissions|C2F6          kt C2F6/yr           2.517838
                                                                       Emissions|C3F8          kt C3F8/yr           0.746671
                                                                       Emissions|C4F10         kt C4F10/yr          0.105177
                                                                       Emissions|C5F12         kt C5F12/yr          0.063553
                                                                       Emissions|C6F14         kt C6F14/yr          0.062998
                                                                       Emissions|C7F16         kt C7F16/yr          0.193044
                                                                       Emissions|C8F18         kt C8F18/yr          0.141468
                                                                       Emissions|CCl4          kt CCl4/yr          34.970595
                                                                       Emissions|CF4           kt CF4/yr           15.819257
                                                                       Emissions|CFC11         kt CFC11/yr         51.585468
                                                                       Emissions|CFC113        kt CFC113/yr         2.662652
                                                                       Emissions|CFC114        kt CFC114/yr         1.159712
                                                                       Emissions|CFC115        kt CFC115/yr         0.025678
                                                                       Emissions|CFC12         kt CFC12/yr         17.087091
                                                                       Emissions|CH2Cl2        kt CH2Cl2/yr      1835.671768
                                                                       Emissions|CH3Br         kt CH3Br/yr        140.445528
                                                                       Emissions|CH3CCl3       kt CH3CCl3/yr        2.015470
                                                                       Emissions|CH3Cl         kt CH3Cl/yr       5376.602241
                                                                       Emissions|CH4           Mt CH4/yr          326.888122
                                                                       Emissions|CHCl3         kt CHCl3/yr        405.429476
                                                                       Emissions|CO            Mt CO/yr           756.447541
                                                                       Emissions|CO2|Biosphere Mt CO2/yr         3434.455691
                                                                       Emissions|CO2|Fossil    Mt CO2/yr        36711.189545
                                                                       Emissions|HCFC141b      kt HCFC141b/yr      57.214803
                                                                       Emissions|HCFC142b      kt HCFC142b/yr      20.830485
                                                                       Emissions|HCFC22        kt HCFC22/yr       316.207542
                                                                       Emissions|HFC125        kt HFC125/yr       179.752639
                                                                       Emissions|HFC134a       kt HFC134a/yr      338.508598
                                                                       Emissions|HFC143a       kt HFC143a/yr       18.467768
                                                                       Emissions|HFC152a       kt HFC152a/yr       35.038457
                                                                       Emissions|HFC227ea      kt HFC227ea/yr       8.977620
                                                                       Emissions|HFC23         kt HFC23/yr         14.630536
                                                                       Emissions|HFC236fa      kt HFC236fa/yr       0.271622
                                                                       Emissions|HFC245fa      kt HFC245fa/yr      11.886443
                                                                       Emissions|HFC32         kt HFC32/yr        165.199336
                                                                       Emissions|HFC365mfc     kt HFC365mfc/yr      6.081212
                                                                       Emissions|HFC4310mee    kt HFC4310/yr        0.563605
                                                                       Emissions|Halon1202     kt Halon1202/yr      0.000000
                                                                       Emissions|Halon1211     kt Halon1211/yr      2.304956
                                                                       Emissions|Halon1301     kt Halon1301/yr      1.096459
                                                                       Emissions|Halon2402     kt Halon2402/yr      0.074954
                                                                       Emissions|N2O           kt N2O/yr        10557.828861
                                                                       Emissions|NF3           kt NF3/yr            4.143707
                                                                       Emissions|NH3           Mt NH3/yr           68.695800
                                                                       Emissions|NMVOC         Mt VOC/yr          187.289161
                                                                       Emissions|NOx           Mt NO2/yr          123.497129
                                                                       Emissions|OC            Mt OC/yr            33.222987
                                                                       Emissions|SF6           kt SF6/yr            9.663222
                                                                       Emissions|SO2F2         kt SO2F2/yr          4.807369

In [7]:
MAGICC_EXE_PATH = Path(
    "../../gcages/tests/regression/cmip7-scenariomip/cmip7-scenariomip-workflow-inputs/magicc-v7.6.0a3/bin"
)
MAGICC_CMIP7_SCENARIOMIP_PROBABILISTIC_CONFIG_FILE = Path(
    "../../gcages/tests/regression/cmip7-scenariomip/cmip7-scenariomip-workflow-inputs/magicc-v7.6.0a3/configs/magicc-ar7-fast-track-drawnset-v0-3-0.json"
)

In [8]:
if platform.system() == "Darwin":
    if platform.processor() == "arm":
        MAGICC_EXE = MAGICC_EXE_PATH / "magicc-darwin-arm64"
        os.environ["DYLD_LIBRARY_PATH"] = "/opt/homebrew/Cellar/gcc/15.2.0_1/lib/gcc/current"

elif platform.system() == "Linux":
    MAGICC_EXE = MAGICC_EXE_PATH / "magicc"

elif platform.system() == "Windows":
    MAGICC_EXE = MAGICC_EXE_PATH / "magicc.exe"

In [9]:
scm_runner = CMIP7ScenarioMIPSCMRunner.from_cmip7_scenariomip_config(
    # Generally, you want to run SCMs in parallel
    n_processes=multiprocessing.cpu_count(),
    magicc_exe_path=MAGICC_EXE,
    magicc_prob_distribution_path=MAGICC_CMIP7_SCENARIOMIP_PROBABILISTIC_CONFIG_FILE,
    historical_emissions_path=CMIP7_SCENARIOMIP_GLOBAL_HISTORICAL_EMISSIONS,
    output_variables=("Surface Air Temperature Change",),
    batch_size_scenarios=15,
)

/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/scmdata/database/_database.py:9: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  import tqdm.autonotebook as tqdman
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(

In [10]:
scm_runner.climate_models_cfgs["MAGICC7"] = scm_runner.climate_models_cfgs[
        "MAGICC7"
][:ENSEMBLE_MEMBERS]

In [11]:
scm_results = scm_runner(scenario_to_run)
scm_results

Climate models:   0%|          | 0/1 [00:00<?, ?it/s]
[WARNING] 10:33:36 - openscm_runner.adapters.magicc7.magicc7: Historical data has not been checked
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/scmdata/run.py:2632: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([ret._meta.to_frame(), *to_join_metas]).astype("category")


Writing SCEN7 files: 100%|██████████| 1.00/1.00 [00:00<00:00, 6.04it/s]


/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
Front serial: 100%|██████████| 2.00/2.00 [00:02<00:00, 1.42s/it]


/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
Front parallel: 100%|██████████| 2.00/2.00 [00:02<00:00, 1.23s/it]


/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/ganti/Documents/code/ar7_netzero_assessment/.venv/lib/python3.13/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(














Parallel runs: 100%|██████████| 596/596 [00:36<00:00, 16.4it/s]

Climate models: 100%|██████████| 1.00/1.00 [00:45<00:00, 45.3s/it]
Scenario batch: 100%|██████████| 1/1 [00:45<00:00, 45.30s/it]
Climate models: 100%|██████████| 1/1 [00:45<00:00, 45.30s/it]

time                                                                                                                              1750  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
...                                                                                                                                ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change   0.0

time                                                                                                                                  1751  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.025523
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.031040
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.030692
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.031590
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.027147
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.017827
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.026252
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.030374
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.028743
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.022891

time                                                                                                                                  1752  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.035245
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.042205
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.040997
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.038679
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.035592
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.023158
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.037221
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.040541
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.033538
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.030484

time                                                                                                                                  1753  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.038705
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.048116
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.045351
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.038038
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.036302
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.024724
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.040805
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.043459
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.032633
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.033864

time                                                                                                                                  1754  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.037403
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.050462
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.045125
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.032724
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.030512
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.023399
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.037859
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.040246
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.028997
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.034510

time                                                                                                                                  1755  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.035409
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.050914
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.044089
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.026720
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.026315
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.022082
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.033536
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.037291
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.023442
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.033935

time                                                                                                                                  1756  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.028824
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.043648
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.036419
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.016755
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.019135
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.017362
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.026930
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.029464
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.013487
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.028245

time                                                                                                                                  1757  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.013995
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.027046
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.019364
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.001728
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.006278
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.008233
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.012388
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.013941
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.000925
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.015128

time                                                                                                                                  1758  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.019164
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.034479
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.027058
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.011589
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.013671
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.013365
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.016612
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.021374
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.011104
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.020858

time                                                                                                                                  1759  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.031390
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.048696
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.041304
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.029319
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.028335
...                                                                                                                                    ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.022044
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.030783
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.036681
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.027028
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  0.031526

time                                                                                                                              ...  \
climate_model  model        region run_id scenario                                           unit variable                        ...
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   1      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   2      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   3      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   4      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
...                                                                                                                               ...
                                   595    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   596    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   597    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   598    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...
                                   599    ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  ...

time                                                                                                                                  2091  \
climate_model  model        region run_id scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  0      ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Air Temperature Change  1.901908

In [12]:
post_processor = CMIP7ScenarioMIPPostProcessor.from_cmip7_scenariomip_config()
post_processed_results = post_processor(
    scm_results.loc[pix.isin(variable=["Surface Air Temperature Change"])]
)

In [13]:
post_processed_results.metadata_categories

climate_model   model         scenario                                               metric
MAGICCv7.6.0a3  AIM/CGE V2.2  ENGAGE-Feasibility-Maximum-Effort/Institutional_NZCO2  category_name    C3: limit warming to 2°C (>67%)
                                                                                     category                                      C3
dtype: object

In [14]:
post_processed_results.metadata_quantile.loc[
    pix.isin(quantile=[0.05, 0.5, 0.95])
].unstack(["quantile", "metric"]).round(2).sort_index(axis="columns")

quantile                                                                                                               0.05  \
metric                                                                                                                 2100
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  1.11
                                                                                      yr   Surface Temperature (GSAT)   NaN

quantile                                                                                                                     \
metric                                                                                                                  max
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  1.28
                                                                                      yr   Surface Temperature (GSAT)   NaN

quantile                                                                                                                        \
metric                                                                                                                max_year
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)      NaN
                                                                                      yr   Surface Temperature (GSAT)   2047.0

quantile                                                                                                               0.50  \
metric                                                                                                                 2100
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  1.58
                                                                                      yr   Surface Temperature (GSAT)   NaN

quantile                                                                                                                    \
metric                                                                                                                 max
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  1.7
                                                                                      yr   Surface Temperature (GSAT)  NaN

quantile                                                                                                                        \
metric                                                                                                                max_year
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)      NaN
                                                                                      yr   Surface Temperature (GSAT)   2049.0

quantile                                                                                                               0.95  \
metric                                                                                                                 2100
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  2.38
                                                                                      yr   Surface Temperature (GSAT)   NaN

quantile                                                                                                                     \
metric                                                                                                                  max
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)  2.41
                                                                                      yr   Surface Temperature (GSAT)   NaN

quantile
metric                                                                                                                max_year
climate_model  model        region scenario                                           unit variable
MAGICCv7.6.0a3 AIM/CGE V2.2 World  ENGAGE-Feasibility-Maximum-Effort/Institutional... K    Surface Temperature (GSAT)      NaN
                                                                                      yr   Surface Temperature (GSAT)   2100.0